### ISSUE TITLE
Build failed in ubuntu 14.04

### ISSUE THREAD

**Issue by eshafeeqe** [jtsiomb/libimago#1]
Please check the following comment.

https://github.com/hikiko/mohawk/issues/1#issuecomment-553422518

Any leads will be appreciated

**Comment by eshafeeqe** [comment]
Please check the following comment.

https://github.com/hikiko/mohawk/issues/1#issuecomment-553422518

Any leads will be appreciated

**Comment by jtsiomb** [comment]
Can't reproduce myself, but I think I might have side-stepped the issue. Try again and let me know if it's fixed.

**Comment by eshafeeqe** [comment]
@jtsiomb Thanks a lot, that fixed the error
